openapi: 3.1.0
info:
  title: Brilho do Sol Nascente API
  version: "1.0.0"
  description: |
    API para gerar narrações com ElevenLabs e transcrever áudios usando Whisper.
servers:
  - url: https://brilho-sol-nascente.onrender.com
    description: Servidor Render (produção)
paths:
  /falar:
    post:
      summary: Gera áudio TTS
      operationId: gerarAudio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                texto:
                  type: string
                  description: Texto a ser narrado
                voice_id:
                  type: string
                  description: ID da voz ElevenLabs
              required:
                - texto
      responses:
        "200":
          description: URL do áudio gerado
          content:
            application/json:
              schema:
                type: object
                properties:
                  audio_url:
                    type: string
  /transcrever:
    post:
      summary: Transcreve áudio e devolve minutagem
      operationId: transcreverAudio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                audio_url:
                  type: string
                  description: URL do áudio a ser transcrito
              required:
                - audio_url
      responses:
        "200":
          description: Transcrição com minutagem
          content:
            application/json:
              schema:
                type: object
