openapi: 3.1.0
info:
  title: DeusTeEnviouIsso API
  version: 1.0.0
  description: |
    Endpoints para geração de áudio, transcrição, pacote de prompts e montagem de vídeo.
servers:
  - url: "https://deus-w0i8.onrender.com"
    description: Servidor principal
paths:
  /falar:
    post:
      operationId: falar
      summary: Gerar TTS com ElevenLabs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                texto:
                  type: string
                  description: Texto ou versículo a ser narrado
              required:
                - texto
      responses:
        "200":
          description: URL do áudio gerado
          content:
            application/json:
              schema:
                type: object
                properties:
                  audio_url:
                    type: string
                  slug:
                    type: string

  /transcrever:
    post:
      operationId: transcrever
      summary: Transcrever áudio via Whisper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                audio_url:
                  type: string
                  description: URL do áudio a ser transcrito
              required:
                - audio_url
      responses:
        "200":
          description: Timestamps e transcrição
          content:
            application/json:
              schema:
                type: object
                properties:
                  duracao_total:
                    type: number
                  transcricao:
                    type: array
                    items:
                      type: object
                      properties:
                        inicio:
                          type: number
                        fim:
                          type: number
                        texto:
                          type: string

  /gerar_csv:
    post:
      operationId: gerar_csv
      summary: Gerar CSV/SRT/TXT e criar pasta no Drive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transcricao:
                  type: array
                  items:
                    type: object
                    properties:
                      inicio:
                        type: number
                      fim:
                        type: number
                      texto:
                        type: string
                prompts:
                  type: array
                  items:
                    type: string
                descricao:
                  type: string
                texto_original:
                  type: string
              required:
                - transcricao
                - prompts
                - texto_original
      responses:
        "200":
          description: Pasta criada no Drive
          content:
            application/json:
              schema:
                type: object
                properties:
                  slug:
                    type: string
                  folder_url:
                    type: string

  /próxima_etapa:
    get:
      operationId: proxima_etapa
      summary: Instruções para envio do ZIP
      responses:
        "200":
          description: Mensagem de transição
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string

  /upload_zip:
    post:
      operationId: upload_zip
      summary: Receber ZIP de imagens e subir imagens selecionadas ao Drive
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                slug:
                  type: string
                folder_id:
                  type: string
                zip:
                  type: string
                  format: binary
      responses:
        "200":
          description: Lista de imagens selecionadas
          content:
            application/json:
              schema:
                type: object
                properties:
                  slug:
                    type: string
                  folder_id:
                    type: string
                  images:
                    type: array
                    items:
                      type: string

  /montar_video:
    post:
      operationId: montar_video
      summary: Montar vídeo com zoom, grão e legendas, e enviar MP4 ao Drive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slug:
                  type: string
                folder_id:
                  type: string
              required:
                - slug
                - folder_id
      responses:
        "200":
          description: Link da pasta com o vídeo
          content:
            application/json:
              schema:
                type: object
                properties:
                  video_url:
                    type: string