name: Keep Render Awake

on:
  schedule:
    - cron: '*/15 * * * *'  # a cada 15 minutos (UTC)
  workflow_dispatch:        # permite execução manual

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          curl -s --max-time 10 https://deus-w0i8.onrender.com || echo "API indisponível"
